---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /  # This line is only needed when deploying on IBM Cloud Private.
  name: k8s-vim-driver-ingress  # The ingress name must be unique for each ingress rule created.
spec:
  rules:
  - host: {{ .Values.app.config.ingress.host }}
    http:
      paths:
      - path: /  # This is the url path used to access the service externally.
        backend:
         serviceName: k8s-vim-driver
         servicePort: 8292
