apiVersion: v1
kind: Service
metadata:
  name: k8s-vim-driver
  labels:
    app: k8s-vim-driver
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8292
    targetPort: 8292
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
    protocol: TCP
    name: http
  selector:
    app: k8s-vim-driver
