## Docker Image for the Openstack VIM Driver
docker:
  ## Make this the full path, including registry host and port if using one
  image: accanto/k8s-vim-driver
  version: 0.3.0.dev0
  imagePullPolicy: IfNotPresent

## Configuration for the application deployment
app:
  ## Number of pods to deploy 
  replicas: 1
  
  ## Configure resource requests and limits for each container of the application
  ## Default is to have no limit
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
    # limits:
    #  cpu: 250m
    #  memory: 384Mi
    # requests:
    #  cpu: 250m
    #  memory: 384Mi

  ## k8s-vim-driver specific configuration
  config:
    kafka:
      ## note: assumes that Kafka is accessible at 'app.config.override.messaging.connection_address'

      ## There is an additional option for configuring access to Kafka by fixed IP. This is added as a host entry to the container.
      hostEnabled: false
      ## the host must match the value of 'app.config.override.messaging.connection_address', if it is set
      host: "foundation-kafka"
      ## this must be set to the Kafka IP address
      ip:

    ## Configure logging 
    log:
      level: DEBUG

    ## Pass additional environment variables to the application containers
    env:
      ## to support indexing of logs in Elasticsearch using Filebeat, we use logstash format. This allows
      ## us to bundle the log message and other metadata in a json log message and let Filebeat extract them
      ## as top level fields in the Elasticsearch index.
      LOG_TYPE: logstash

      ## configuration for WSGI container
      ## WSGI_CONTAINER can be uwsgi or gunicorn
      WSGI_CONTAINER: uwsgi
      ## the number of processes and threads to spawn to handle requests
      NUM_PROCESSES: "4"
      NUM_THREADS: "2"

    ingress:
      ## The host used to access the service externally i.e. http://<server.ingress.hostname>/
      ## If not making use of a DNS to resolve this host you must add this to the client hosts file with the K8s IP
      ## E.g.
      ## 10.220.1.2     k8s.lm
      host: k8s.lm

    ## k8s_config.yml (driver configuration) overrides
    override:
      messaging:
        # Kafka connection url
        connection_address: foundation-kafka:9092
      jobqueue:
        replication_factor: 1
        num_partitions: 1
        config:
          # 1 day
          retention_ms: 86400000
          file_delete_delay_ms: 86400000

service:
  # Using NodePort allows access to the IPs through http://k8s-host:nodePort/
  type: NodePort
  nodePort: 31637
